module.exports = [
  {
    eslintName: "timeout",
    ruleId: "VITEST-FLK-001",
    ruleName: "TimeoutRule",
    description:
      "Detect tests that use setTimeout which can cause timing-dependent flakiness",
  },
  {
    eslintName: "date-mock",
    ruleId: "VITEST-FLK-002",
    ruleName: "DateMockRule",
    description:
      "Detect tests that use Date/Date.now() without vi.useFakeTimers()",
  },
  {
    eslintName: "network-import",
    ruleId: "VITEST-FLK-003",
    ruleName: "NetworkImportRule",
    description: "Detect network-related imports in test files",
  },
  {
    eslintName: "fake-timers-cleanup",
    ruleId: "VITEST-FLK-004",
    ruleName: "FakeTimersCleanupRule",
    description: "Detect missing fake timers cleanup",
  },
  {
    eslintName: "non-deterministic",
    ruleId: "VITEST-FLK-005",
    ruleName: "NonDeterministicRule",
    description: "Detect non-deterministic test patterns",
  },
  {
    eslintName: "no-assertion",
    ruleId: "VITEST-MNT-001",
    ruleName: "NoAssertionRule",
    description: "Detect tests with no assertions",
  },
  {
    eslintName: "multiple-expect",
    ruleId: "VITEST-MNT-002",
    ruleName: "MultipleExpectRule",
    description: "Detect tests with too many expect calls",
  },
  {
    eslintName: "conditional-logic",
    ruleId: "VITEST-MNT-003",
    ruleName: "ConditionalLogicRule",
    description: "Detect conditional logic inside tests",
  },
  {
    eslintName: "try-catch",
    ruleId: "VITEST-MNT-004",
    ruleName: "TryCatchRule",
    description: "Detect try/catch blocks inside tests",
  },
  {
    eslintName: "empty-test",
    ruleId: "VITEST-MNT-005",
    ruleName: "EmptyTestRule",
    description: "Detect empty test blocks",
  },
  {
    eslintName: "nested-describe",
    ruleId: "VITEST-STR-001",
    ruleName: "NestedDescribeRule",
    description: "Detect deeply nested describe blocks",
  },
  {
    eslintName: "return-in-test",
    ruleId: "VITEST-STR-002",
    ruleName: "ReturnInTestRule",
    description: "Detect return statements inside tests",
  },
  {
    eslintName: "missing-await-assertion",
    ruleId: "VITEST-MNT-006",
    ruleName: "MissingAwaitAssertionRule",
    description: "Detect un-awaited async assertions",
  },
  {
    eslintName: "focused-test",
    ruleId: "VITEST-MNT-007",
    ruleName: "FocusedTestRule",
    description: "Detect .only() and fit() usage",
  },
  {
    eslintName: "missing-mock-cleanup",
    ruleId: "VITEST-MNT-008",
    ruleName: "MissingMockCleanupRule",
    description: "Detect mocks without cleanup",
  },
  {
    eslintName: "weak-assertion",
    ruleId: "VITEST-MNT-009",
    ruleName: "WeakAssertionRule",
    description: "Detect weak assertions like toBeTruthy/toBeFalsy",
  },
  {
    eslintName: "implementation-coupled",
    ruleId: "VITEST-MNT-010",
    ruleName: "ImplementationCoupledRule",
    description: "Detect tests coupled to implementation details",
  },
  {
    eslintName: "test-id-negative-presence",
    ruleId: "VITEST-MNT-011",
    ruleName: "TestIdNegativePresenceRule",
    description:
      "Detect getByTestId usage paired with negative presence assertions",
  },
  {
    eslintName: "banned-module-mock",
    ruleId: "VITEST-DEP-001",
    ruleName: "BannedModuleMockRule",
    description: "Detect mocking of stable dependencies",
  },
  {
    eslintName: "production-singleton-import",
    ruleId: "VITEST-DEP-002",
    ruleName: "ProductionSingletonImportRule",
    description: "Detect production singleton imports in tests",
  },
  {
    eslintName: "reset-escape-hatch",
    ruleId: "VITEST-DEP-003",
    ruleName: "ResetEscapeHatchRule",
    description: "Detect overuse of reset escape hatches",
  },
  {
    eslintName: "mock-export-validation",
    ruleId: "VITEST-DEP-004",
    ruleName: "MockExportValidationRule",
    description: "Detect mock factory exports that don't match the real module",
  },
  {
    eslintName: "valid-expect",
    ruleId: "VITEST-VAL-001",
    ruleName: "ValidExpectRule",
    description: "Detect invalid expect() usage",
  },
  {
    eslintName: "valid-expect-in-promise",
    ruleId: "VITEST-VAL-002",
    ruleName: "ValidExpectInPromiseRule",
    description: "Detect missing await on expect in promises",
  },
  {
    eslintName: "valid-describe-callback",
    ruleId: "VITEST-VAL-003",
    ruleName: "ValidDescribeCallbackRule",
    description: "Detect invalid describe() callbacks",
  },
  {
    eslintName: "valid-title",
    ruleId: "VITEST-VAL-004",
    ruleName: "ValidTitleRule",
    description: "Detect invalid test/describe titles",
  },
  {
    eslintName: "no-unneeded-async-expect-function",
    ruleId: "VITEST-VAL-005",
    ruleName: "NoUnneededAsyncExpectFunctionRule",
    description: "Detect unnecessary async expect function usage",
  },
  {
    eslintName: "no-standalone-expect",
    ruleId: "VITEST-NO-001",
    ruleName: "NoStandaloneExpectRule",
    description: "Detect expect calls outside of tests",
  },
  {
    eslintName: "no-identical-title",
    ruleId: "VITEST-NO-002",
    ruleName: "NoIdenticalTitleRule",
    description: "Detect duplicate test titles",
  },
  {
    eslintName: "no-commented-out-tests",
    ruleId: "VITEST-NO-003",
    ruleName: "NoCommentedOutTestsRule",
    description: "Detect commented-out test cases",
  },
  {
    eslintName: "no-test-prefixes",
    ruleId: "VITEST-NO-005",
    ruleName: "NoTestPrefixesRule",
    description: "Detect use of xit/fit test prefixes",
  },
  {
    eslintName: "no-duplicate-hooks",
    ruleId: "VITEST-NO-006",
    ruleName: "NoDuplicateHooksRule",
    description: "Detect duplicate lifecycle hooks",
  },
  {
    eslintName: "no-import-node-test",
    ruleId: "VITEST-NO-007",
    ruleName: "NoImportNodeTestRule",
    description: "Detect imports from node:test in Vitest files",
  },
  {
    eslintName: "no-interpolation-in-snapshots",
    ruleId: "VITEST-NO-008",
    ruleName: "NoInterpolationInSnapshotsRule",
    description: "Detect template interpolation in snapshot matchers",
  },
  {
    eslintName: "no-large-snapshots",
    ruleId: "VITEST-NO-009",
    ruleName: "NoLargeSnapshotsRule",
    description: "Detect overly large inline snapshots",
  },
  {
    eslintName: "no-done-callback",
    ruleId: "VITEST-NO-013",
    ruleName: "NoDoneCallbackRule",
    description: "Detect done callback pattern in tests",
  },
  {
    eslintName: "no-conditional-expect",
    ruleId: "VITEST-NO-014",
    ruleName: "NoConditionalExpectRule",
    description: "Detect expect calls inside conditional blocks",
  },
  {
    eslintName: "prefer-to-be",
    ruleId: "VITEST-PREF-001",
    ruleName: "PreferToBeRule",
    description: "Enforce using toBe over toEqual for primitives",
  },
  {
    eslintName: "prefer-to-contain",
    ruleId: "VITEST-PREF-002",
    ruleName: "PreferToContainRule",
    description: "Enforce using toContain over toEqual with array includes",
  },
  {
    eslintName: "prefer-to-have-length",
    ruleId: "VITEST-PREF-003",
    ruleName: "PreferToHaveLengthRule",
    description: "Enforce using toHaveLength over checking .length",
  },
  {
    eslintName: "prefer-spy-on",
    ruleId: "VITEST-PREF-005",
    ruleName: "PreferSpyOnRule",
    description: "Enforce vi.spyOn over vi.fn for existing methods",
  },
  {
    eslintName: "prefer-called-once",
    ruleId: "VITEST-PREF-007",
    ruleName: "PreferCalledOnceRule",
    description: "Enforce toHaveBeenCalledOnce over toHaveBeenCalledTimes(1)",
  },
  {
    eslintName: "prefer-hooks-on-top",
    ruleId: "VITEST-PREF-009",
    ruleName: "PreferHooksOnTopRule",
    description: "Enforce hooks placed before tests in describe blocks",
  },
  {
    eslintName: "prefer-hooks-in-order",
    ruleId: "VITEST-PREF-010",
    ruleName: "PreferHooksInOrderRule",
    description:
      "Enforce hooks in beforeAll > beforeEach > afterEach > afterAll order",
  },
  {
    eslintName: "prefer-todo",
    ruleId: "VITEST-PREF-012",
    ruleName: "PreferTodoRule",
    description: "Enforce using test.todo for empty test stubs",
  },
  {
    eslintName: "prefer-mock-promise-shorthand",
    ruleId: "VITEST-PREF-013",
    ruleName: "PreferMockPromiseShorthandRule",
    description:
      "Enforce vi.fn().mockResolvedValue over manual promise wrappers",
  },
  {
    eslintName: "prefer-expect-resolves",
    ruleId: "VITEST-PREF-014",
    ruleName: "PreferExpectResolvesRule",
    description: "Enforce expect().resolves over awaiting inside expect",
  },
  {
    eslintName: "require-hook",
    ruleId: "VITEST-REQ-001",
    ruleName: "RequireHookRule",
    description: "Enforce setup/teardown logic in hooks, not at top level",
  },
  {
    eslintName: "require-top-level-describe",
    ruleId: "VITEST-REQ-002",
    ruleName: "RequireTopLevelDescribeRule",
    description: "Enforce all tests inside describe blocks",
  },
  {
    eslintName: "require-to-throw-message",
    ruleId: "VITEST-REQ-003",
    ruleName: "RequireToThrowMessageRule",
    description: "Enforce error message assertions on toThrow",
  },
  {
    eslintName: "consistent-test-it",
    ruleId: "VITEST-CON-001",
    ruleName: "ConsistentTestItRule",
    description: "Enforce consistent use of test vs it",
  },
  {
    eslintName: "consistent-vitest-vi",
    ruleId: "VITEST-CON-003",
    ruleName: "ConsistentVitestViRule",
    description: "Enforce consistent import of vi from vitest",
  },
  {
    eslintName: "hoisted-apis-on-top",
    ruleId: "VITEST-CON-004",
    ruleName: "HoistedApisOnTopRule",
    description: "Enforce vi.hoisted and vi.mock calls at top of file",
  },
  {
    eslintName: "pw-wait-for-timeout",
    ruleId: "VITEST-PW-001",
    ruleName: "PwWaitForTimeoutRule",
    description: "Detect waitForTimeout causing flaky waits",
  },
  {
    eslintName: "pw-css-id-selector",
    ruleId: "VITEST-PW-002",
    ruleName: "PwCssIdSelectorRule",
    description: "Detect CSS ID selectors in Playwright locators",
  },
  {
    eslintName: "pw-xpath-selector",
    ruleId: "VITEST-PW-003",
    ruleName: "PwXPathSelectorRule",
    description: "Detect XPath selectors in Playwright locators",
  },
  {
    eslintName: "pw-locator-nth",
    ruleId: "VITEST-PW-004",
    ruleName: "PwLocatorNthRule",
    description: "Detect .nth() positional locators",
  },
  {
    eslintName: "pw-arbitrary-sleep",
    ruleId: "VITEST-PW-010",
    ruleName: "PwArbitrarySleepRule",
    description:
      "Detect arbitrary sleep/page.waitForTimeout in Playwright tests",
  },
  {
    eslintName: "pw-evaluate-inner-text",
    ruleId: "VITEST-PW-006",
    ruleName: "PwEvaluateInnerTextRule",
    description: "Detect page.evaluate(el => el.innerText) patterns",
  },
  {
    eslintName: "pw-text-assertion-over-role",
    ruleId: "VITEST-PW-007",
    ruleName: "PwTextAssertionOverRoleRule",
    description:
      "Detect text-based assertions that should use role-based locators",
  },
  {
    eslintName: "pw-test-id-over-semantic-role",
    ruleId: "VITEST-PW-008",
    ruleName: "PwTestIdOverSemanticRoleRule",
    description:
      "Detect data-testid where semantic role locators are available",
  },
  {
    eslintName: "pw-duplicate-spec-file",
    ruleId: "VITEST-PW-009",
    ruleName: "PwDuplicateSpecFileRule",
    description: "Detect duplicate spec file patterns",
  },
  {
    eslintName: "pw-page-dollar",
    ruleId: "VITEST-PW-005",
    ruleName: "PwPageDollarRule",
    description: "Detect page.$() raw queries",
  },
  {
    eslintName: "pw-hard-css-class-chain",
    ruleId: "VITEST-PW-011",
    ruleName: "PwHardCssClassChainRule",
    description: "Detect brittle CSS class chains in selectors",
  },
  {
    eslintName: "pw-missing-web-first-assertion",
    ruleId: "VITEST-PW-012",
    ruleName: "PwMissingWebFirstAssertionRule",
    description: "Detect missing web-first assertions in Playwright",
  },
  {
    eslintName: "pw-missing-axe-scan",
    ruleId: "VITEST-PW-100",
    ruleName: "PwMissingAxeScanRule",
    description: "Detect missing axe-core accessibility scans",
  },
];
